DROP DATABASE IF EXISTS xanadu_test_db;
CREATE DATABASE xanadu_test_db;
USE xanadu_test_db;

DROP TABLE IF EXISTS albums;
CREATE TABLE albums(
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  ARTIST VARCHAR(240),
  NAME VARCHAR(240) NOT NULL,
  RELEASE_DATE INT,
  SALES FLOAT,
  GENRE VARCHAR(240)
);